### ISSUE TITLE
Import from php array

### ISSUE THREAD

**Issue by bambamboole** [bigbridge-nl/product-import#1]
Hi,

is it possible to import products from an php array?

**Comment by patrick-bigbridge** [comment]
Hello Manuel,

The main reason why I chose a class-based input specification over array-based specification is that when the data is complex, the nested array structures become unreadable (I think).

Examples of specification by array can be found here: http://avstudnitz.github.io/AvS_FastSimpleImport/products.html
And real-life cases can even become much more complex than that.

Furthermore class-based spec. allows for autocompletion by your IDE, which is handy. And input by function calls allows for some immediate input validation.
