### ISSUE TITLE
Removing select attribute

### ISSUE THREAD

**Issue by haelbichalex** [bigbridge-nl/product-import#10]
Hi again!

I want to clear out a custom select attribute. I tried two things:
`$global->setCustomAttribute("report_number", null);` and `$global->setSelectAttribute("report_number", null);`.

![bildschirmfoto 2019-02-21 um 17 44 48](https://user-images.githubusercontent.com/15052352/53186149-b7057980-3600-11e9-8940-3a21ea7edd62.png)

I somehow think I already this this with the first approach some time ago, did this change maybe?

Regards,
Alex

**Comment by garfix** [comment]
Hi Alex,

Using setSelectAttribute with null as a value did not work before version 1.2.7, it should work now. Using setCustomAttribute with null has always worked. Can I see more of your code?

greetings!
Patrick

**Comment by haelbichalex** [comment]
alright... I found my error
I wanted to clear the attribute from a non existing product 😥 copied it by hand so I didn't even check the logs because I thought it can't be wrong...

Good to know it works with setSelectAttribute now as well 👍
