### ISSUE TITLE
Issue with category levels

### ISSUE THREAD

**Issue by choleaoum** [bigbridge-nl/product-import#16]
Hey, just wanted to toss out a quick issue in regards to importing categories. The categories are being created one level too high. The script creates categories one level too high due to the parentId of the first level being set too high (it's setting to level 3 it should be level 2).

I resolved it by changing line 253 from file ../Model/Resource/Resolver/CategoryImporter.php

`$parentLevel = count($idPath);`

to

`$parentLevel = count($idPath) - 1;`

I compared my results with a category I created using the admin page with "Default Category" being the parent category and it starts the new category at level 2.

This was an issue for anyone using ElasticSuite, it wasn't properly allowing us to navigate through category filters.

**Comment by garfix** [comment]
Yes, you are right. Thanks for reporting it. There's a bug in the creation of categories. The "level" field catalog_category_entity is set 1 too high. Also the "position" of the new category within the parent category is not calculated right, but that's probably not so important.

I would like to make the following changes to fix this, can you check for me if this helps, before I create a new release:

The function now starts with

```
        $categoryEntityTable = $this->metaData->categoryEntityTable;
        $urlRewriteTable = $this->metaData->urlRewriteTable;
        $attributeSetId = $this->metaData->defaultCategoryAttributeSetId;

        $parentLevel = count($idPath) - 1;
        $childLevel = $parentLevel + 1;
        $parentId = $idPath[$parentLevel];
        $parentPath = implode(self::CATEGORY_ID_PATH_SEPARATOR, $idPath);

        // update parent data
        $this->db->execute("

```

and in the calculation of $position a bit below that in the same function

```
$position = $this->db->fetchSingleCell("
            SELECT MAX(`position`)
            FROM `{$categoryEntityTable}`
            WHERE `path` LIKE ? AND level = ?
        ", [
            "{$parentPath}/%",
            $childLevel
        ]);
```

Note that $parentLevel was changed to $childLevel

**Comment by choleaoum** [comment]
Hey sorry for the slow response, as I was testing the update I forgot that I should mention there's a trimming issue. I'm using CData to pass some special values into the category & description. XML does not like these values. Anyways, when being passed 

In the ElementHandler.php 

I changed line 395 to 

`$value = trim($this->characterData); `

Line 406 to

`$this->product->addCategoriesByGlobalName(array_map('trim', $this->items));`

To remove any additional whitespacing. I'm still in the process of testing, just figured I post this now before I forget.

**Comment by patrick-bigbridge** [comment]
No need to apologize for a slow response. I am not in a hurry ;)

Thanks for showing the missing trim(). Only I will place it in the Product and ProductStoreView classes for this use is more general. I noticed more trims were needed there as well.

I hope you find some more bugs. Name them here and when you're done I will create a single new release.

I need some more information if you want to have the image to be deleted. Are you using the ImportConfig::$imageStrategy 'set', for instance?

Check ImportConfig::$existingImageStrategy for options you can use to import images from remote locations.

**Comment by choleaoum** [comment]
When you import from a remote location, I believe it downloads it and then caches it locally correct?

And sure, I hope to use this in production sometime this week. Working out all the kinks, but it's been a great extension so far.

**Comment by patrick-bigbridge** [comment]
Hi @choleaoum 

I am planning to close this issue and create a new release for the fixes. Is there anything you would like to add?

**Comment by patrick-bigbridge** [comment]
I created a new release and close this issue.
