### ISSUE TITLE
Reset product data to use default values

### ISSUE THREAD

**Issue by haelbichalex** [bigbridge-nl/product-import#2]
Hi,

First of all, thank you for sharing your great work!

So I used your importer to create a product within the `global` store view and the `default` store view. Unfortunately we now need to reset all the data from `default` to use the default `global` values.

Here is my code:
```
$global = $product->global();
$global->setName($this->_productData['name']);

$default = $product->storeView('default');
$default->setName($this->_productData['name']);

$importer->importSimpleProduct($product);
$importer->flush();
```

Here is what I tried so far, but without success:
```
$default->setName(NULL);
```

Is this even possible?

**Comment by patrick-bigbridge** [comment]
Hello!

Thanks for using the library and for asking the question!

What you are doing looks fine and should work. I just created a test scenario that does what I think you are doing, and it succeeded. Simple "scalar" attributes can be removed from the database by setting them to null. So if you want to keep the values at the global level and remove the values from store view "default" you need to do

```
$global = $product->global();
$global->setName($this->_productData['name']);

$default = $product->storeView('default');
$default->setName(null);

$importer->importSimpleProduct($product);
$importer->flush();
```

If this still doesn't work, tell me what exactly does not work: do you get an error ($product->getErrors()) or is the attribute just not removed from the table catalog_product_entity_varchar (with store_id from default)? And if possible show me all relevant code you use to import products.

Good luck!
