### ISSUE TITLE
Mangeto 2.4.1 - Tier Price not created when website is specified.

### ISSUE THREAD

**Issue by goddanao** [bigbridge-nl/product-import#21]
Hello,
using this code the tier price is not set. If i omit the website code it works, setting the tier price for all the websites.

```php
$pr = new SimpleProduct($sku);
$pr->setTierPrices([
    new TierPrice(1,$price, 'my_customers_group', 'my_website')
]);
```

**Comment by patrick-bigbridge** [comment]
Hello Andrea,

In the advanced pricing / tier price section of the product, in the backend, are you able to specify a specific website, when adding a tier price? Or is "All Websites" the only option? If so, you may want to set prices to "website", in configuration / catalog / catalog / price / Catalog Price Scope.

Also, check table catalog_product_entity_tier_price if the price is actually imported (even though not visible in the backend).

**Comment by goddanao** [comment]
Thank you Patrick,
Catalog Price Scope wasn't website.
