### ISSUE TITLE
Error "is not an integer"

### ISSUE THREAD

**Issue by Aquive** [bigbridge-nl/product-import#23]
Hi,

I am facing in an issue.

When importing a value for a custom attribute it throws the following error. The attribute is a dropdown.

`color is not an integer (blue) for product 'test' that starts in line 3`

I am expecting the importer to just insert the value "blue". But it is not. Am i doing something wrong?

**Comment by garfix** [comment]
Hello Akif,

If you import a custom attribute like this

`$product->global()->setCustomAttribute('color', 'blue');`

product-import will try to import the literal value, and will not convert the label to an option value (integer).

If the attribute is dropdown, you should use this:

`$product->global()->setSelectAttribute('color', 'blue');`

product-import will then treat the value as a label and look up the option value.

**Comment by Aquive** [comment]
@garfix thanks! Works, fixed.
