### ISSUE TITLE
Can images be replaced and not appended to? Category separator escaping?

### ISSUE THREAD

**Issue by chrisastley** [bigbridge-nl/product-import#24]
Hi,

Thanks for the great work you have done with the import module. I have it up and working as expected other than 2 issues moving forward based on how it used to work with Magmi.

1. When I used to import products with Magmi it had the option to either overwrite images or append? Your module appears to only append and I need it to replace images. Would this be something that could be added?
2. In Magmi you can escape a slash in the category name, for example;
`Default Category/Car Parts/Brakes/Seals \/ Repair Parts`
This worked great, is there anyway to do this, at the moment it added a category called 'Seals \ ' with another child called 'Repair Parts'

Thanks

**Comment by patrick-bigbridge** [comment]
Thanks Chris!

Images can be replaced by changing the "image strategy", as follows:

 $config->imageStrategy = ImportConfig::IMAGE_STRATEGY_SET;

In stead of escaping the category, you can specify a different category path separator with the property "categoryNamePathSeparator", for example "Default Category#Car Parts#Brakes#Seals / Repair Parts"

$config->categoryNamePathSeparator = "#";

If you're using XML import, look for the options `path-separator` and `image`.

**Comment by chrisastley** [comment]
Hi Patrick,

Many thanks for the speedy reply. I'm using XML via Rest. 

I can see the notes for `path-separator` but not `image` here https://github.com/bigbridge-nl/product-import/blob/master/doc/xml-webapi-import.md 

Am I looking in the wrong place?

**Comment by patrick-bigbridge** [comment]
That's the right place, but I forgot to document this option. It should read:

image=set

I updated the page just now.

**Comment by chrisastley** [comment]
Great, thanks for the updated info. I'd managed to find it digging into the source code and also found another option I can't find in the documentation.

In this file vendor/bigbridge/product-import/Api/ImportConfig.php 

`    /**
     * How to deal with the imported categories?
     * - add: link products to categories named in the import
     * - set: like add, and delete links too
     *
     * Important!
     * The 'set' option compares existing product-to-category links with the ones mentioned in the import.
     * Existing links that are not named in the import are removed.
     * Consider the possibility that a shop administrator manually adds products to categories that are not part of the import,
     * such as "New" or "Sale". The importer will remove these links and undo the work of a shop administrator.
     * So, use this option only if you are certain that the shop administrator does not add products to categories manually.
     *
     * @var string
     */
    public $categoryStrategy = self::CATEGORY_STRATEGY_ADD;

    const CATEGORY_STRATEGY_ADD = 'add'; // Only add and update category links
    const CATEGORY_STRATEGY_SET = 'set'; // Add and update category links; and also remove existing category links not named in the import`

But I can't see this option in the following file;
vendor/bigbridge/product-import/Api/ProductImportWebApi.php

Is this as simple as me adding the option in or is the functionality not working?

**Comment by chrisastley** [comment]
Great, will keep an eye out for the next release.

**Comment by patrick-bigbridge** [comment]
I went through all options in the cli command and the Rest API. I put the options in the same order and added documentation.

Created a new release: 1.5.3

**Comment by chrisastley** [comment]
Thank you, all working as expected now.

**Comment by garfix** [comment]
That's good to hear. For now I'll close this issue, and if you find anything else, just open a new issue.
