### ISSUE TITLE
How to use --url-key-strategy.

### ISSUE THREAD

**Issue by IvoJongmans** [bigbridge-nl/product-import#25]
Hi,

First of all. Great work on this import tool. 

I'm trying to run an import with a set of five products. Two products share the same url-key. This gives a error during the import. I came across the --url-key-strategy option. This should be able to fix these errors during import right? I've tried a lot of combinations where I want to use the 'add-sku' option. I couldn't get it to work. Can you give me a clear example of how to use this? 

Right now I'm running something like: 

bin/magento bigbridge:product:import **--url-key-strategy add-sku** --auto-create-categories --dry-run test.xml

And I've tried a lot of other possibilities :) 

Thanks in advance.

**Comment by patrick-bigbridge** [comment]
Hello Ivo, thank you!

I just did a quick check if this actually still works, and I was happy to find that it does. I used doc/example/a-basic-product.xml and duplicated the product into a second one, while only changing the sku.

The sku is only added if necessary. It won't be added for the first product, but it will be added for the second and further products.

Your command line options are correct. What exactly happens? Did you get an error? Which one?

Can you share the xml with two of the conflicting products? You can obfuscate product names if you like.

**Comment by IvoJongmans** [comment]
Hi Patrick,

Thanks for the quick response. I've added my .xml file that I use for the product import. Change .txt extension to .xml.

[exportProducts.txt](https://github.com/bigbridge-nl/product-import/files/5855564/exportProducts.txt) (Can't upload XML's here)

 I've also added a screenshot with the error I get on my CLI. 

![ERRORCLI](https://user-images.githubusercontent.com/48712793/105487801-f6d3b080-5cb0-11eb-99e8-9834da0d4c07.png)

**Comment by patrick-bigbridge** [comment]
Thanks, yes it's clear to me now.

The importer works like this: you can _either_ specify a url_key explicitly, _or_ have the importer generate one for you. If you specify one yourself, you are responsible for making sure that it's unique.

Only if you tell the importer to generate a url key, based on the name of the product, you can tell it what to do if the generated url key already exists.

A url key is generated if you remove the <url_key> attribute and add 

`<generate_url_key>1</generate_url_key>`

I wanted to respond to you quickly, and that means I haven't taken the time yet to think if the use case you present is acceptable. I will get back to you on this.

**Comment by IvoJongmans** [comment]
Hi,

Using `<generate_url_key>1</generate_url_key>` on global and storeview levels solved my problems. Thanks for the quick replies.
