### ISSUE TITLE
website_codes restapi

### ISSUE THREAD

**Issue by chrisastley** [bigbridge-nl/product-import#26]
Hi,

I've been adding products and just realised I have an issue. I'm pushing products to 4 x Magento2 websites using restapi method.
3 x Magento sites only have a single website/store/storeview and they work as expected.
The 4th website has 3 website/store/storeviews setup and when I use the same import the products aren't assigned to any of the websites.

I currently haven't included the website_codes element in the XML but all the 3 single website sites are assigning correctly, I expected the 4th to assign to the main base but it does not.

Is this a bug or feature to assign automatically to single website stores?

Thanks in advance.

**Comment by patrick-bigbridge** [comment]
Hi Chris,

Websites must be assigned to products explicitly, they are never added automatically, so I am a little surprised that this worked for you in some cases. :)

**Comment by chrisastley** [comment]
Thanks for the clarification. Yes, it worked for all sites with only a single website and is already assigned.

**Comment by patrick-bigbridge** [comment]
As I remember it, and I just checked the code to be certain, the importer only assigned products to websites that have been named explicitly. One of the principles of the importer is to only to import that which is given and use no "magic". So I suppose some other process (Magento itself?) must have added the product-website link, after the import had completed.

Does this help you enough?

**Comment by chrisastley** [comment]
Yeah thats absolutely fine. I've looked in the code myself too and couldn't see anything. Must be Magento doing the magic based on an assumption that if there is only a single website it makes sense to assign it.
