### ISSUE TITLE
Image import creates hardlinks

### ISSUE THREAD

**Issue by IvoJongmans** [bigbridge-nl/product-import#31]
Hi,

When I'm importing products with a .XML file hardlinks er being created for the images. This causes problems when running backups on the server. 

Is there any way to circumvent or fix this? 

I import images over HTTPS:

`<image file_or_url="https://www.example.nl/media/catalog/product/g/d/gdpr.jpg">`

Thanks in advance.

Ivo

**Comment by patrick-bigbridge** [comment]
Hi Ivo,

Can you explain the problem with the backups? Some files are not backed up, or are you getting errors?

Before I add another config option just to copy files instead of hard linking, I would like to understand exactly what problem it solves.

Is the fact that you import images over HTTPS relevant to the problem? I don't understand.

**Comment by IvoJongmans** [comment]
Hi,

We receive the following error when making a backup: 

The following hard links have been found under User test: 

        /home/example/domains/example.shop/magento2/pub/media/catalog/product/p/l/pl430-c_1.jpg

        /home/example/domains/example.shop/magento2/pub/media/import/1a87ad567cc236002eadc98ae40b4d0f-pl430-c_1.jpg

This causes the backup process to terminate. 

![image](https://user-images.githubusercontent.com/48712793/106609935-6de92e80-6566-11eb-8547-46f405334933.png)


When looking up this particular inode we see the hardlinks in the /import and /catalog folder.

The fact that I'm using HTTPS isn't relevant. You'll get the same result using local images. I just wanted to point out the method that I was using. Maybe this was relevant for  a quick answer.

**Comment by patrick-bigbridge** [comment]
Hello Ivo,

Just a quick question: a small search tells me that you probably use DirectAdmin and that this is a security precaution that may or may not be relevant to your case and that may be disabled. Are you per chance in the position to disable this setting?

https://forum.directadmin.com/threads/cant-make-any-admin-backup-anymore.46810/
https://help.directadmin.com/item.php?id=658

**Comment by Aquive** [comment]
@patrick-bigbridge quick question. Why is a file also being copied to /pub/media/import? And can this be removed or afterwards or just disabled?

**Comment by patrick-bigbridge** [comment]
Images may be removed from media/import afterwards; it is a temporary directory, used by the caching mechanism. It is only used to avoid downloading the image.

**Comment by patrick-bigbridge** [comment]
Ivo, have any of the options mentioned helped you? Or is adding a new option to the importer the only way to get this problem fixed?

**Comment by IvoJongmans** [comment]
Hi Patrick,

We've been able to resolve this problem by removing the images from the media/import directory. Thanks again.

**Comment by patrick-bigbridge** [comment]
Sorry to come back to this issue I just closed myself. I just wanted to let you know that I had some time to look at the code and found it easy to have the temporary images removed after the import (when they are not needed for caching). So I created a new release for it: 1.6.1

**Comment by IvoJongmans** [comment]
Thanks!
