### ISSUE TITLE
Please provide example of how to use post method with webapi?

### ISSUE THREAD

**Issue by curiousfellas** [bigbridge-nl/product-import#34]
Can you give me any example of how to do that?
Can you also provide any example feed that i can import to test with my Magento store?
Can you also specify how to add dynamic xml payload to the post request sent to the server endpoint?

**Comment by patrick-bigbridge** [comment]
Hello @curiousfellas 

You can find a small PHP example in the integration tests:

https://github.com/bigbridge-nl/product-import/blob/master/Test/ApiFunctional/RestApiTest.php

Example xml payloads are in the doc/example directory.

**Comment by curiousfellas** [comment]
Do you know about any xml feed i can import and test with my store?

**Comment by patrick-bigbridge** [comment]
I have placed several types of feeds in the example directory

https://github.com/bigbridge-nl/product-import/tree/master/doc/example

Here's "a-basic-product.xml"

```
<?xml version="1.0" encoding="UTF-8"?>
<import>
	<simple sku="skinny-jeans-811">
		<attribute_set_name>Default</attribute_set_name>
		<global>
			<name>Skinny Jeans 811</name>
			<price>19.95</price>
			<status>1</status>
			<visibility>4</visibility>
			<tax_class_name>Taxable Goods</tax_class_name>
			<generate_url_key>1</generate_url_key>
		</global>
		<store_view code="default">
			<price>19.75</price>
		</store_view>
		<category_global_names>
			<item>Default Category/Trousers</item>
			<item>Default Category/Trendy</item>
		</category_global_names>
		<website_codes>
			<item>base</item>
		</website_codes>
		<stock>
			<qty>12</qty>
			<is_in_stock>1</is_in_stock>
		</stock>
	</simple>
</import>

```

**Comment by curiousfellas** [comment]
I mean that do you have any site from which I can import a sample feed?

Best Regards
CuriousFellas

**Comment by patrick-bigbridge** [comment]
Ah, no, these feeds are not exported by any system. They must be created by a programmer.

This product importer helps a programmer who wishes to import many products quickly. The feeds need to be produced by hand, though.

**Comment by patrick-bigbridge** [comment]
Can you tell me something you are trying to accomplish? That may help me give you better directions.

**Comment by curiousfellas** [comment]
I have this third party website like techdata and i have a to send a post request to their specified url with xml payload and then in the response they will send me a xml response. I need to parse that response and import the products provided with the response received by magento site.

**Comment by patrick-bigbridge** [comment]
Ok, in that case you may just want to use the library of the importer. Read the products from the xml and import them with code like this

```
$importer = $factory->createImporter($config);

    foreach ($lines as $i => $line) {

        $product = new SimpleProduct($line[1]);

        // global eav attributes
        $global = $product->global();
        $global->setName($line[0]);
        $global->setPrice($line[2]);

        // German eav attributes
        $german = $product->storeView('de_store');
        $german->setName($line[3]);
        $german->setPrice($line[4]);

        $importer->importSimpleProduct($product);
    }

    // process any remaining products in the pipeline
    $importer->flush();
```

**Comment by patrick-bigbridge** [comment]
What you're describing is a classic use case of the library: you need to import products from an external system with a custom feed-layout and you need it done simple and quick.

**Comment by patrick-bigbridge** [comment]
This issue #27 gives you a more elaborate use.

**Comment by patrick-bigbridge** [comment]
Closing this issue for now. Feel free to reopen if you have further questions.
