### ISSUE TITLE
How to set salable quantity ?

### ISSUE THREAD

**Issue by jchirschy** [bigbridge-nl/product-import#36]
Hello,

I'm using the importer library with the help of https://github.com/bigbridge-nl/product-import/issues/27#issuecomment-766370678 and it works like a charm.

But I don't know how to set the default stock so that salable quantity is right.
I'm doing something like that : 

```
$product->defaultStockItem()->setQty($quantity);
$product->defaultStockItem()->setIsInStock(true);
$product->sourceItem("default")->setQuantity($quantity);
$product->sourceItem("default")->setStatus(1); // in stock
$product->sourceItem("default")->setNotifyStockQuantity(20);
```

In Magento dashboard / catalog / products, the column `Quantity` is correctly set, but the salable quantity indicates `Default stock: 0`. If I open the product and save it, the salable quantity is calculated the right way.

Did I miss something or there is an issue ?

Thanks for you help.

**Comment by patrick-bigbridge** [comment]
To be honest, i don't know. I see you are using source items. I have implemented basic support for MSI, but we have never had the need for it, so I have no experience with it.

**Comment by patrick-bigbridge** [comment]
Where can I find the salable quantity that you mention? Is it a column in the product overview?

**Comment by jchirschy** [comment]
Yes, it is a column in the products overview. And in the item view, it is called `Product Salable Quantity `. 
I'm using Magento 2.3.2

Do you think it is related to MSI ?

**Comment by patrick-bigbridge** [comment]
I think so, I don't see it in the shops where we removed MSI from composer.
Product Salable Quantity probably is not a primary field, but rather a calculated field that depends on several quantity fields and config settings.
I suppose you've tried reindexing?

**Comment by jchirschy** [comment]
Hello,

I've cleared the cache and flushed and thought I was doing everything useful, but my bad, I forgot to reindex and that was it. Very sorry.

Have a good day and thanks for your precious help.
