### ISSUE TITLE
Export category attribute values

### ISSUE THREAD

**Issue by IvoJongmans** [bigbridge-nl/product-import#39]
Hi,

Is it possible to export attribute values from categories like meta description, meta title and meta keywords?  

Thanks in advance.

Ivo

**Comment by patrick-bigbridge** [comment]
Hello Ivo,

I think you mean "import"? I have no plans to import more category attributes. It is not the focus of the library and it cannot be added easily.

**Comment by IvoJongmans** [comment]
You're right, I meant "import". Thanks for your quick reply.
