### ISSUE TITLE
 Trying to get property 'path' of non-object in Model/Resource/Storage/UrlRewriteStorage.php on line 376

### ISSUE THREAD

**Issue by duckchip** [bigbridge-nl/product-import#40]
## Issue

Hi guys,

I'm using this module to run a product import with only simple products and ran into the following issue: 

`
Trying to get property 'path' of non-object in /var/www/store1/magento2/releases/20210416100919/vendor/bigbridge/product-import/Model/Resource/Storage/UrlRewriteStorage.php on line 376 [] []
`

Any idea what might be wrong?

Thx in advance!

## Versions
Magento 2.4.2
bigbridge/product-import 1.7.0

**Comment by patrick-bigbridge** [comment]
Thanks, @duckchip !
I included your pull request into release 1.7.1
