### ISSUE TITLE
The setSelectAttribute method does not fill swatch input on Text Swatch

### ISSUE THREAD

**Issue by davinanaya** [bigbridge-nl/product-import#44]
Hello, first of all I want to thank you for creating this library that is really useful, it improves performance considerably

My issue is the following, if I create an attribute as Text Swatch it only fills the description and not the Swatch field, then in the front it is always showing a null value but aria-label shows what is in the description field

<img width="934" alt="Screen Shot 2021-06-17 at 10 49 27 PM" src="https://user-images.githubusercontent.com/19170814/122504762-8a8b7d80-cfc0-11eb-93b9-7b351b62a062.png">

Thanks for you help.

**Comment by patrick-bigbridge** [comment]
Hi @davinanaya 

Nice to hear it's useful :)

I will look into this as soon as I can.

**Comment by patrick-bigbridge** [comment]
Hello @davinanaya 

The library primarily imports products. It does not import attributes. However, it makes an exception for the admin-values of selection attribute options (dropdown and multiple select) as an extra service. Text and Visual Swatch attribute options are also imported, but again only their admin values (called "Description" in Text Swatches). 

Once the attribute options are imported, additional data will have to be added manually. In this case the Swatch values will have to be added manually. 

I hope you understand this reasoning and that it will not cause you too much extra work.

**Comment by davinanaya** [comment]
I see, as a quick fix i will use a simple dropdown instead of Text Swatches, this should fix the issue 

Regards thanks
