### ISSUE TITLE
Fetching Magento configurations isn't working as expected

### ISSUE THREAD

**Issue by hostep** [bigbridge-nl/product-import#47]
Hi!

The code I find over [here](https://github.com/bigbridge-nl/product-import/blob/e8b06f2de7b10a1fb9f2adc7ccacceaa2ef3a1d1/Model/Resource/MetaData.php#L681-L712) for fetching the configuration for the product url suffix, is not correct because it doesn't take all the ways into consideration for how we can determine configurations in Magento.

As far as I'm aware, the following things are checked in Magento do determine the value of a configuration setting, from highest prio to lowest:
- environment variables
- setting defined in the `app/etc/env.php` file
- setting defined in the `app/etc/config.php` file
- setting stored in the database
- setting's default value

Currently your code only supports the last two as far as I can see.
Is there a good reason why you aren't using the `ScopeConfigInterface` to fetch configuration values? It supports all those scenario's I've listed above and does the right thing.

For example.
We have no value for `catalog/seo/product_url_suffix` in our database, but our `app/etc/config.php` file contains the following:

```php
<?php

return [
    'modules' => [
        // ...
    ],
    'system' => [
        'default' => [
            'catalog' => [
                'seo' => [
                    'product_url_suffix' => '',
                ]
            ]
        ]
    ]
];
```

However, your module takes `.html` as suffix (which is its default value in the `config.xml` file of a module) instead of an empty value like we would expect it.

I would strongly recommend you to switch to using the `ScopeConfigInterface` from core Magento for fetching these kind of config values, so all config values you fetch work as expected.

Thanks for considering this! 🙂

**Comment by patrick-bigbridge** [comment]
Haha, no there is no good reason. This seemed to be an easy thing at first; then the code needed to be extended and extended. And now you show correctly that it is still insufficient.

I will rewrite the code as soon as I can find some time.

**Comment by hostep** [comment]
PR https://github.com/bigbridge-nl/product-import/pull/48 created

**Comment by patrick-bigbridge** [comment]
Awesome! Yes this is much much better. Thanks for taking the time to improve the code. 
I will go over your code to check if some edge cases were not affected (when time allows it).
